name: Build and test image then upload to ECR
on:
  workflow_call:
    inputs:
      branch:
        description: "Valid branch: feature, develop"
        required: true
        type: string
      project-name:
        description: "Name of the project"
        required: true
        type: string
      aws-region:
        description: "AWS region of ECR repo"
        required: true
        type: string
      sonar-args:
        description: "Additional sonar arguments"
        required: false
        type: string
        default: ""
    secrets:
      aws-role:
        description: "AWS role to use"
        required: true
      sonar-token:
        description: "Sonar token"
        required: true
      sonar-host-url:
        description: "Sonar host"
        required: true
      ecr-repo:
        description: "ECR repo"
        required: true
      build-args:
        description: "Build arguments"
        required: false
defaults:
  run:
    shell: bash
    working-directory: .

jobs:
  input-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check Inputs
        run: |
          [[ "${{ secrets.build-args }}" == "" || "${{ secrets.build-args }}" =~ ^[A-Za-z0-9\_\-]+=([A-Za-z0-9\_\-]+|internal-[A-Za-z0-9\_\-]+\.${{ inputs.aws-region }}\.elb\.amazonaws\.com)\
          (\ [A-Za-z0-9\_\-]+=([A-Za-z0-9\_\-]+|internal-[A-Za-z0-9\_\-]+\.${{ inputs.aws-region }}\.elb\.amazonaws\.com))*$ ]] || \
          (echo "Unexpected build-args - must be formatted like arg_name=value where value can contain numbers and letters \
          or be an internal lb url in same region, multiple args must be delimited by a single space" && false)
          [[ "${{ inputs.branch }}" =~ ^(feature/[A-za-z0-9\_\-]+|develop)$ ]] || (echo "Unexpected branch - must be feature or develop" && false)

  build:
    needs: input-check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Docker image runs tests
        run: grep -E "pytest|npm test" Dockerfile && echo "Confirmed tests are being run in Dockerfile" || echo "Please include test stage in Dockerfile - currently only checking for pytest and npm test"
      
      - name: Build Docker image
        run: |
          build_args=""
          for arg in ${{ secrets.build-args }}
          do
            build_args+="--build-arg $arg "
          done
          docker build -t ${{ inputs.project-name }}:$GITHUB_SHA $build_args .
        
  scan:
    needs: input-check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        id: scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.sonar-token }}
          SONAR_HOST_URL: ${{ secrets.sonar-host-url }}
          INPUT_PROJECTBASEDIR: .
        with:
          args: >
            -Dsonar.projectKey=${{ inputs.project-name }}
            -Dsonar.sources=.
            -Dsonar.qualitygate.wait=true
            -Dsonar.qualitygate.timeout=120
            ${{ inputs.sonar-args }}
            
  upload:
    if: ${{ inputs.branch == 'develop' }}
    needs: [input-check, build, scan]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.aws-role }}
          aws-region: ${{ inputs.aws-region }}

      - name: Build Docker image
        run: |
          build_args=""
          for arg in ${{ secrets.build-args }}
          do
            build_args+="--build-arg $arg "
          done
          docker build -t ${{ inputs.project-name }}:$GITHUB_SHA $build_args .

      - name: Login to ECR
        run: aws ecr get-login-password --region ${{ inputs.aws-region }} | docker login --username AWS --password-stdin ${{ secrets.ecr-repo }}

      - name: Tag image and upload to ECR
        id: tag_upload
        run: |
          docker tag ${{ inputs.project-name }}:$GITHUB_SHA ${{ secrets.ecr-repo }}/${{ inputs.project-name }}:$GITHUB_SHA
          docker push ${{ secrets.ecr-repo }}/${{ inputs.project-name }}:$GITHUB_SHA