name: Terraform Drift Check
on:
  workflow_call:
    inputs:
      branch:
        description: "Valid branch: main"
        required: true
        type: string
      project-name:
        description: "Name of the project"
        required: true
        type: string
      aws-region:
        description: "Default AWS region for infrastructure"
        required: true
        type: string
      copy-args:
        description: "Copy arguments - if need to copy any files/folders into working directory"
        required: false
        type: string
        default: ""
      tf-vars:
        description: "Terraform template arguments"
        type: string
        required: false
        default: ""
    secrets:
      aws-role:
        description: "AWS role to use"
        required: true
defaults:
  run:
    shell: bash
    working-directory: .
jobs:
  input-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check Inputs
        run: |
          [[ "${{ inputs.branch }}" == "main" ]] \
          || (echo "Unexpected branch - must be main" && false)
          [[ "${{ inputs.project-name }}" == "" ]] && (echo "Project name cannot be empty" && false)
          [[ "${{ inputs.aws-region }}" == "" ]] && (echo "AWS region cannot be empty" && false)
          [[ "${{ inputs.tf-vars }}" == "" || "${{ inputs.tf-vars }}" =~ ^[a-z\_]+=([a-z0-9\-]+|https?:\/\/[a-z0-9\.\-\\\?\=\&]+)(\ [a-z\_]+=([a-z0-9\-]+|https?:\/\/[a-z0-9\.\-\\\?\=\&]+))*$ ]] \
          || (echo -e "Unexpected tf-vars - must be formatted like arg_name=value:\
          \n\t- arg_name can only contain lowercase letters and underscores\
          \n\t- value can contain lowercase letters, numbers and  hyphens or be a url\
          \n\t- multiple args must be delimited by a single space" \
          && false)

  check:
    needs: input-check
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: ${{ inputs.project-name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: "main"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.aws-role }}
          aws-region: ${{ inputs.aws-region }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Copy in common templates
        if: ${{ inputs.copy-args != '' }}
        run: cp ${{ inputs.copy-args }} .

      - name: Drift check
        run: |
          tf_args=""
          for arg in ${{ inputs.tf-vars }}
          do
            tf_args+="-var $arg "
          done
          terraform plan $tf_args | sed -e "s|$(echo ${{ secrets.aws-role }} | grep -o "[0-9]\+")|<awsAccountId>|g | tee /dev/tty \
          | grep -o "No changes..*Your infrastructure matches the configuration." && echo "No drift detected" || (echo "Drift detected - check logs && false)"
